spring.application.name=student-api
spring.datasource.url=jdbc:h2:mem:testdb

spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# JWT Configuration
jwt.secret=your-secret-key-change-this-in-production-make-it-long-enough-for-hs512
jwt.expiration=86400000
